---
title: Збереження свого проєкту Scratch
hero_image: images/banner.png
description: Збереження свого проєкту Scratch
listed: false
copyedit: true
steps:
  - 
    title: Збереження свого проєкту Scratch
