---
title: ஒரு ஸ்க்ராட்ச் திட்டத்தை சேமிக்க
hero_image: படங்கள்/banner.png
description: ஒரு ஸ்க்ராட்ச் திட்டத்தை சேமிக்க
listed: false
copyedit: true
steps:
  - 
    title: உங்கள் திட்டத்தை சேமிக்கவும்
