---
title: Pagse-save ng isang Scratch project
hero_image: images/banner.png
description: Pagse-save ng isang Scratch project
listed: false
copyedit: true
steps:
  - 
    title: I-save ang iyong proyekto
