---
title: Scratch ව්‍යාපෘතියක් සුරකීම(saving)
hero_image: images / banner.png
description: Scratch ව්‍යාපෘතියක් සුරකීම(saving)
listed: false
copyedit: true
steps:
  - 
    title: ඔබගේ ව්යාපෘතිය සුරකින්න
